# Generated by Django 4.2 on 2025-04-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
