# Generated by Django 4.2 on 2025-04-22 06:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
