# Generated by Django 4.2 on 2025-04-22 09:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_artist_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
