# Generated by Django 4.2 on 2025-04-22 10:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_song_artist_song_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
    ]
