# Generated by Django 4.2 on 2025-05-03 17:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
