# Generated by Django 4.2 on 2025-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_album_artist_album_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('artist', 'Artist')], default='user', max_length=10),
        ),
    ]
