# Generated by Django 4.2 on 2025-05-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_playlist_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
