# Generated by Django 4.2 on 2025-05-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_role'),
        ('api', '0012_playlistsong'),
    ]

    operations = [
    ]
